pool: MyAgentPool
steps:
- bash: echo hello world
- task: DotNetCoreCLI@2
  inputs:
- task: DotNetCoreCLI@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    command: 'build'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'